роутинг, реализация авторизации
blackmozzzart/Stellar-Burgers pull request #5
Opened 2023-07-01 13:50 UTC by blackmozzzart

2023-07-01 14:14 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Настроены все редиректы
- Хорошая работа с формами
- Правильно реализовали работу с деталями ингредиента

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- На странице профиля невозможно ничего ввести в инпуты. А кнопка "Сохранить" вызывает перезагрузку страницы.
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя. 

Для этого используйте обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```
**Можно лучше**

- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью ` return <Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate`)
- После успешного восстановления пароля юзера стоит перекидывать на страницу логина

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-01 14:14 UTC, andryxxa93 commented on src/pages/register/register.jsx
> +    const passChange = (e) => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-07-01 14:14 UTC, andryxxa93 commented on src/components/App/App.tsx
> +          <Route path='/login' element={<PublicRouteElement element={<Login />} />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-08 13:53 UTC, blackmozzzart commented
https://github-production-user-asset-6210df.s3.amazonaws.com/60173362/251963798-7823f247-a4bb-426c-ad41-815e601aa44e.png
если я сделаю так как по заданию, у меня перестает работать logout и обновление измененных данных

2023-07-10 05:55 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-10 18:00 UTC, merged